# Generated by Django 5.2.13 on 2026-04-14 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Munyabugingo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_view_admin_dashboard', 'Can view administrative dashboard')]},
        ),
    ]
